language: node_js
sudo: false
node_js: stable
addons: 
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin local
env:
  global:
  - secure: oUEmbfheRfyoovQmDLrtrOlxrcG7GDmLrPWoz3RwVZlK2L7YZla+VC0s2x2HBAxxPVArgnKYhX3ZEopNCfz55xhi12AoJZjhLRf6HbFCCQMunCtfXgNWhj+aZ1vw0r3oNksP00a5PdtptN/B47Kknb3y6BaEqZ+umLpvJZOxWid8WRHHnAuE7NcWhuXo8KKp9yMfm1y7f3T07UdAGQClejAdQqAgLRTf9Z5PYGMWtnkh73rtIjIdg6TiZzwoVDuGQsNcourq6/g4CN82CPPJFlFsFU+G8CBaFDbDPEjQLzxOH0wa4CzmyjrwbfEQTAnN1X1RKaqkScGPSgxvohea1c2X7al2+xZyjUeqbiILKiLvYc3t/rMA+EUeIEiA8w3Fxa6cQZ5DYat2kbjJd2pZMXYfivgEKBNZ/oq/SOfUPJ0rsWkhamVZaOd0964wKZkIGvgdD9fsJ2Xw6dSmik07zO0Nf8hm8PCEaD+Pjk1pI8HxM7NnlZTW4yYTk1jEbqxkvl80NGvA5cuQPiINy1U2LAuNZhf6U7x73yyW1uyBuiYPKgGG1kpq1Ghj+Ij5v+kFk2AzSD5BZEEZ/ietPN0kAM6lNZNB9PHxtSrebnQgw5ADRUryQRf6XLEESEqtb2JgrnizYtuvu/zeKwOx7Xw9b3BE5FDR/MDO7/A5EA4DEJo=
  - secure: TS5Mf1p3Me6hrZvi5NdETIZnreSEA2DkCQFlSTbAtYGbPTMXPKXUOZZ94Lh6rU/9eU0hypLYOsSHAo279sJINxhCeZfM3Itkgce6OdjyeaUsdMYzWHJCmQfy76uaoq6rmmMUYVSiR9R7cOx9MhIe3hpMO53e8f3B/APkVEZUNOd7YYSVSfVHMN4AhCGMN68gFku2z2W9EjTrksxvvSjf4DUyrCPv1wM2Z5qXvPg1lSVOMz9yJ28qIP0RMdV/iX3ifJZhM1149QzuYehcKVj+oFK4eF8SbBHN0ZlPPVcCxJ16Pv4WmHWlctLrD61A83dsBU5QYhJUe2YNyqBQocyD9YtxO9YPQjIWlp6qwACu1b7Q+CzPabRjbHhxwhCbSIXBM6rmXjILlHogXucuYQnykFElbQQsuc5vf50DoEiFIpBkFkDOjsCzm4s2i7BYlE7n/CzpgpRRBbN78hSwRnWg9AUWNYMRhElUfJA+503Qkx1KlznSADIQ2EdHqVtogmo2rfQsQA0UkguhUUVo2P0vq56W1Y9nnfh+Qy2J8TO0+ztlp7AeQIfdb0HAgeMf0st38c3CM6wNfWU5RWYZcixPLdUajJTpM1Wbqv5MmlfmATWSNvARp58WaHoPYGPFuCnt6kjoIQSvm3bWdtN7HfX6c/0KerijcN50uzZ/q3KSBpc=
